kind: Secret
apiVersion: v1
metadata:
  name: mongodb-secret
  namespace: chat-app
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
  JWT_SECRET: a8f3c9e2d7b41f6a9c2e7d8b3f4a1c9e5d6f7a8b9c1d2e3f4a5b6c7d8e9f0a1
