kind: Secret
apiVersion: v1
metadata:
  name: mongodb-secret
  namespace: chat-app
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleQ==
